# More info at https://docs.rspamd.com/modules/hfilter

hfilter {
  helo_enabled = false;      # HELO patterns and DNS/FQDN checks
  hostname_enabled = false;  # reverse DNS/hostname patterns
  url_enabled = false;       # URL-only / one-line content
  from_enabled = false;      # MAIL FROM domain checks and bounce
  rcpt_enabled = false;      # recipient sanity (e.g. bounces to many rcpts)
  mid_enabled = false;       # Message-Id domain checks
}
